### ISSUE TITLE
User pool voting story

### ISSUE THREAD

**Issue by humberto-pereira** [humberto-pereira/love-running#1]
To **give my opinion about the best time for running and best track** as a **user**, I can **vote anonymously**
# Acceptance Criteria:
* The poll options should be set as a checkbox.
* The check box should be visible close to the submit button.
* The check box should include an anonymous option.
## Tasks

- [x] Test all inplemantitons
- [x] Implement check box options
- [x] Implement pool campaign
