### ISSUE TITLE
USER STORY: Implement a poll as a Administrator

### ISSUE THREAD

**Issue by humberto-pereira** [humberto-pereira/love-running#2]
In order to **collect user feedback** as a **administrator**, I can **implement a poll**
## Acceptance Criteria:
* The poll options should be set with the options based on the user story.
* The poll should have an anonymous option as the last of the checkbox list.
* The result of the pool should be published in the testimonials section.
## Tasks

- [ ] Implement the (HTML, CSS, and javascript) pool update functionality code
- [ ] Implement poll expiring dates code
- [ ] Implement poll report code
- [ ]  Test all functionalities
